// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://utbpukksvvjglqyghtun.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InV0YnB1a2tzdnZqZ2xxeWdodHVuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYxNjA5MzAsImV4cCI6MjA3MTczNjkzMH0.t14TvsKa0DCbPZB5lTFIV1lJbNfkI78dbLxC1ppN9-Y";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);